# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'stealthy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Stealthy
  pod 'Blockstack', :git => 'https://github.com/AC-FTW/blockstack-ios.git', :branch => 'stealthy_blockstack'

  #pod 'Firebase/Core'
  #pod 'Firebase/Core', '~> 4.13.0'
  #pod 'Firebase/Auth'
  #pod 'Firebase/Database'
  #pod 'Firebase/Messaging'

  #pod 'react-native-config', :path => '../node_modules/react-native-config'

  #pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  #pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
  end

  target 'stealthyTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
