# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'stealthy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Stealthy
  pod 'Blockstack', :git => 'https://github.com/AC-FTW/blockstack-ios.git', :branch => 'stealthy_blockstack'
  pod 'Amplitude-iOS', '~> 4.3.1'
  #pod 'react-native-config', :path => '../node_modules/react-native-config'
  #pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  #pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
  end

  target 'stealthyTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
