# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'stealthy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Stealthy
  #pod 'Blockstack', :git => 'https://github.com/Blockstack/Blockstack-ios.git', :branch => 'rn-test'
  #pod 'Blockstack', :git => 'https://github.com/michalciurus/blockstack-ios.git', :branch => 'objc_support'
  #pod 'Blockstack', :git => 'https://github.com/AC-FTW/blockstack-ios.git', :branch => 'encryption'
  pod 'Blockstack', :git => 'https://github.com/AC-FTW/blockstack-ios.git', :branch => 'stealthy_encryption_blockstack'
  #pod 'Blockstack', :git => 'https://github.com/AC-FTW/blockstack-ios.git', :branch => 'experiment/enc_dec_content'

  #pod 'Firebase'
  #pod 'Firebase' # To enable Firebase module, with `@import Firebase` support
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  #pod 'FirebaseAnalytics'
  pod 'Firebase/Messaging'

  #pod 'react-native-config', :path => '../node_modules/react-native-config'

  #pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  #pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'stealthyTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
